load("//Config:buck_rule_macros.bzl", "framework")

#海螺相关文件根目录，以及
framework(
    name = "Halo",
    deps = [
        "//Halo/Extension:Extension",
    ],
)

#海螺的xib文件
apple_resource(
    name = "Xib",
    visibility = ["PUBLIC"],
    dirs = [],
    files = glob([
        "**/*.xib",
    ]),
)
#海螺的图标文件
apple_asset_catalog(
  name = "Icons",
  dirs = [
    "HL.xcassets",
  ],
  visibility = ["PUBLIC"],
)